/* Generated By:JavaCC: Do not edit this line. PrismExpressionParser.java */
package epmc.prism.expression;
import epmc.prism.error.ProblemsPRISM;
import static epmc.error.UtilError.ensure;
import epmc.error.EPMCException;
import epmc.operator.Operator;
import epmc.operator.OperatorIte;
import epmc.operator.OperatorEq;
import epmc.operator.OperatorNe;
import epmc.operator.OperatorAdd;
import epmc.operator.OperatorSubtract;
import epmc.operator.OperatorLe;
import epmc.operator.OperatorLt;
import epmc.operator.OperatorGe;
import epmc.operator.OperatorGt;
import epmc.operator.OperatorMultiply;
import epmc.operator.OperatorDivide;
import epmc.prism.operator.OperatorPRISMPow;
import epmc.operator.OperatorMax;
import epmc.operator.OperatorMin;
import epmc.operator.OperatorCeil;
import epmc.operator.OperatorFloor;
import epmc.operator.OperatorLog;
import epmc.operator.OperatorMod;
import epmc.expression.*;
import epmc.expression.standard.ExpressionIdentifierStandard;
import epmc.expression.standard.ExpressionFilter;
import epmc.expression.standard.ExpressionMultiObjective;
import epmc.expression.standard.ExpressionCoalition;
import epmc.expression.standard.ExpressionQuantifier;
import epmc.expression.standard.ExpressionSteadyState;
import epmc.expression.standard.ExpressionLiteral;
import epmc.expression.standard.ExpressionOperator;
import epmc.expression.standard.FilterType;
import epmc.expression.standard.TimeBound;
import epmc.expression.standard.CmpType;
import epmc.expression.standard.DirType;
import static epmc.prism.expression.UtilPrismExpressionParser.*;
import epmc.expression.standard.ExpressionTypeReal;
import epmc.expression.standard.ExpressionTypeBoolean;
import epmc.expression.standard.ExpressionTypeInteger;

import java.util.ArrayList;
import java.util.List;

public final class PrismExpressionParser implements PrismExpressionParserConstants {
        private static enum UnType {
                NEXT,
                FINALLY,
                GLOBALLY
        };

        private static enum BinType {
                UNTIL,
                RELEASE,
                WEAK
        };

        private final static class OldSchoolFilter {
                private final FilterType type;
                private final Expression states;
                private final InfoExpression info;

                OldSchoolFilter(FilterType type, Expression states, InfoExpression info) {
                        this.type = type;
                        this.states = states;
                        this.info = info;
                }

                FilterType getType() {
                        return type;
                }

                Expression getStates() {
                        return states;
                }

                InfoExpression getInfo() {
                  return info;
                }
        };

        private Object part;
        private int initialLine;
        private int initialColumn;
        private String string;
        private int errorLine;
        private int errorColumn;

        private void computeErrorPosition(int tline, int tcolumn) {
                errorLine = tline + initialLine - 1;
                errorColumn = tcolumn;
                if (tline == 1) {
                        errorColumn += initialColumn - 1;
                }
        }

        public Expression parseExpression(Object part, int line, int column, String string)  {
                this.part = part;
                this.initialLine = line;
                this.initialColumn = column;
                this.string = string;

                try {
                        return parseCompleteExp();
                } catch (ParseException pe) {
                        Token errorToken = getToken(1);
                        if (errorToken.kind == UNEXPECTED_CHAR) {
                                computeErrorPosition(errorToken.endLine, errorToken.endColumn);
                                ensure(false, ProblemsPRISM.EXPRESSION_PARSER_UNEXPECTED_CHARACTER, newPositional(errorLine, errorColumn), errorToken.image);
                        } else {
                                computeErrorPosition(errorToken.beginLine, errorToken.beginColumn);
                                ensure(false, ProblemsPRISM.EXPRESSION_PARSER_SYNTAX_ERROR, newPositional(errorLine, errorColumn), errorToken.toString());
                        }
                        return null;
        } catch (EPMCException e) {
                   throw e;
                }
                catch (Throwable t) {
                  ensure(false, ProblemsPRISM.EXPRESSION_PARSER_GENERAL_ERROR, t, t);
                  return null;
                }
        }

        public Expression parseExpressionAsProperty(Object part, int line, int column, String string)  {
                this.part = part;
                this.initialLine = line;
                this.initialColumn = column;
                this.string = string;

                try {
                        return parseCompleteProp();
                } catch (ParseException pe) {
                        Token errorToken = getToken(1);
                        if (errorToken.kind == UNEXPECTED_CHAR) {
                                computeErrorPosition(errorToken.endLine, errorToken.endColumn);
                                ensure(false, ProblemsPRISM.EXPRESSION_PARSER_UNEXPECTED_CHARACTER, newPositional(errorLine, errorColumn), errorToken.image);
                        } else {
                                computeErrorPosition(errorToken.beginLine, errorToken.beginColumn);
                                ensure(false, ProblemsPRISM.EXPRESSION_PARSER_SYNTAX_ERROR, newPositional(errorLine, errorColumn), errorToken.toString());
                        }
                        return null;
                } catch (EPMCException e) {
                   throw e;
                } catch (Throwable t) {
                          ensure(false, ProblemsPRISM.EXPRESSION_PARSER_GENERAL_ERROR, t, t);
                          return null;
                }
        }

        private void beginExpression(InfoExpression info) {
          assert info != null;
          info.setPart(part);
          info.setInitialLine(initialLine);
          info.setInitialColumn(initialColumn);
          info.setLine(getToken(1).beginLine);
          info.setColumn(getToken(1).beginColumn);
          info.setStart(getToken(1).offset);
        }

        private void endExpression(InfoExpression info) {
          assert info != null;
          info.setEnd(getToken(0).offset + getToken(0).toString().length());
        }

  final private Expression parseCompleteExp() throws ParseException {
        Expression e;
    e = parseExp(true);
    jj_consume_token(0);
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseCompleteProp() throws ParseException {
        Expression e;
        Expression label = null;
    if (jj_2_1(2147483647)) {
      label = parseLabel();
      jj_consume_token(COLON);
    } else {
      ;
    }
    e = parseExp(false);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SEMICOLON:
      jj_consume_token(SEMICOLON);
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    jj_consume_token(0);
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseExpTemporal(boolean parseExp) throws ParseException {
        Expression e;
    e = parseTemporalBinary(parseExp);
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseExp(boolean parseExp) throws ParseException {
        Expression e;
    e = ExpressionITE(parseExp);
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionITE(boolean parseExp) throws ParseException {
        Expression prop;
        Expression propThen;
        Expression propElse;
        InfoExpression info = new InfoExpression(string);
      beginExpression(info);
    prop = ExpressionImplies(parseExp);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case QUESTION:
      jj_consume_token(QUESTION);
      propThen = ExpressionImplies(parseExp);
      jj_consume_token(COLON);
      propElse = ExpressionITE(parseExp);
          endExpression(info);
                  prop = newOperator(OperatorIte.ITE,
                prop, propThen, propElse, info);
      break;
    default:
      jj_la1[1] = jj_gen;
      ;
    }
          {if (true) return prop;}
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionImplies(boolean parseExp) throws ParseException {
        Expression p;
        Expression nextProp;
        InfoExpression info = new InfoExpression(string);
      beginExpression(info);
    p = ExpressionIff(parseExp);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IMPLIES:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_1;
      }
      jj_consume_token(IMPLIES);
      nextProp = ExpressionIff(parseExp);
                  endExpression(info);
                  p = implies(p, nextProp, info);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionIff(boolean parseExp) throws ParseException {
        Expression p;
        Expression nextProp;
        InfoExpression info = new InfoExpression(string);
      beginExpression(info);
    p = ExpressionOr(parseExp);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IFF:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      jj_consume_token(IFF);
      nextProp = ExpressionOr(parseExp);
                  endExpression(info);
                  p = iff(p, nextProp, info);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionOr(boolean parseExp) throws ParseException {
        Expression p;
        Expression nextProp;
        InfoExpression info = new InfoExpression(string);
     beginExpression(info);
    p = ExpressionAnd(parseExp);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      jj_consume_token(OR);
      nextProp = ExpressionAnd(parseExp);
                  endExpression(info);
                  p = or(p, nextProp, info);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionAnd(boolean parseExp) throws ParseException {
        Expression p;
        Expression nextProp;
        InfoExpression info = new InfoExpression(string);
    beginExpression(info);
    p = ExpressionNot(parseExp);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_4;
      }
      jj_consume_token(AND);
      nextProp = ExpressionNot(parseExp);
         endExpression(info);
          p = and(p, nextProp, info);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionNot(boolean parseExp) throws ParseException {
          Expression p;
        InfoExpression info = new InfoExpression(string);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
             beginExpression(info);
      jj_consume_token(NOT);
      p = ExpressionNot(parseExp);
             endExpression(info);
             p = not(p, info);
      break;
    case CEIL:
    case FALSE:
    case FILTER:
    case FLOOR:
    case FUNCTION:
    case LOG:
    case MAX:
    case MIN:
    case MOD:
    case MULTIOBJECTIVE:
    case P:
    case PMAX:
    case PMIN:
    case POW:
    case R:
    case RMAX:
    case RMIN:
    case S:
    case SMAX:
    case SMIN:
    case SQRT:
    case TRUE:
    case MINUS:
    case LPAR:
    case QUOTE:
    case COALITION_OPEN:
    case IDENTIFIER:
    case NUM_INT:
    case NUM_REAL:
      p = ExpressionEqNe(parseExp);
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionEqNe(boolean parseExp) throws ParseException {
        Expression p;
        Expression nextProp;
        Operator type;
        InfoExpression info = new InfoExpression(string);
      beginExpression(info);
    p = ExpressionROp(parseExp);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ:
      case NEQ:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_5;
      }
      type = EqNe();
      nextProp = ExpressionROp(parseExp);
          endExpression(info);
         p = newOperator(type, p, nextProp, info);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Operator EqNe() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQ:
      jj_consume_token(EQ);
                  {if (true) return OperatorEq.EQ;}
      break;
    case NEQ:
      jj_consume_token(NEQ);
                  {if (true) return OperatorNe.NE;}
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionROp(boolean parseExp) throws ParseException {
        Expression p;
        Expression nextProp;
        Operator type;
        InfoExpression info = new InfoExpression(string);
    beginExpression(info);
    p = ExpressionPlusMinus(parseExp);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEQ:
      case LT:
      case GT:
      case GEQ:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_6;
      }
      type = LtGtLeGe();
      nextProp = ExpressionPlusMinus(parseExp);
          endExpression(info);
          p = newOperator(type, p, nextProp, info);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Operator LtGtLeGe() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LT:
      jj_consume_token(LT);
                  {if (true) return OperatorLt.LT;}
      break;
    case LEQ:
      jj_consume_token(LEQ);
                  {if (true) return OperatorLe.LE;}
      break;
    case GT:
      jj_consume_token(GT);
                  {if (true) return OperatorGt.GT;}
      break;
    case GEQ:
      jj_consume_token(GEQ);
                  {if (true) return OperatorGe.GE;}
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionPlusMinus(boolean parseExp) throws ParseException {
        Expression p;
        Expression nextProp;
        Operator type;
        InfoExpression info = new InfoExpression(string);
      beginExpression(info);
    p = ExpressionTimesDivide(parseExp);
    label_7:
    while (true) {
      if (jj_2_2(2147483647)) {
        ;
      } else {
        break label_7;
      }
      type = PlusMinus();
      nextProp = ExpressionTimesDivide(parseExp);
                  endExpression(info);
                  p = newOperator(type, p, nextProp, info);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Operator PlusMinus() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
      jj_consume_token(PLUS);
                  {if (true) return OperatorAdd.ADD;}
      break;
    case MINUS:
      jj_consume_token(MINUS);
                  {if (true) return OperatorSubtract.SUBTRACT;}
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionTimesDivide(boolean parseExp) throws ParseException {
        Expression p;
        Expression nextProp;
        Operator type;
        InfoExpression info = new InfoExpression(string);
      beginExpression(info);
    p = ExpressionUnaryMinus(parseExp);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TIMES:
      case DIVIDE:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_8;
      }
      type = TimesDivide();
      nextProp = ExpressionUnaryMinus(parseExp);
                  endExpression(info);
                  p = newOperator(type, p, nextProp, info);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Operator TimesDivide() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIMES:
      jj_consume_token(TIMES);
                  {if (true) return OperatorMultiply.MULTIPLY;}
      break;
    case DIVIDE:
      jj_consume_token(DIVIDE);
                  {if (true) return OperatorDivide.DIVIDE;}
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionUnaryMinus(boolean parseExp) throws ParseException {
        Expression p;
        InfoExpression info = new InfoExpression(string);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
            beginExpression(info);
      jj_consume_token(MINUS);
      p = ExpressionUnaryMinus(parseExp);
                  endExpression(info);
                  p = addInverse(p, info);
      break;
    case CEIL:
    case FALSE:
    case FILTER:
    case FLOOR:
    case FUNCTION:
    case LOG:
    case MAX:
    case MIN:
    case MOD:
    case MULTIOBJECTIVE:
    case P:
    case PMAX:
    case PMIN:
    case POW:
    case R:
    case RMAX:
    case RMIN:
    case S:
    case SMAX:
    case SMIN:
    case SQRT:
    case TRUE:
    case LPAR:
    case QUOTE:
    case COALITION_OPEN:
    case IDENTIFIER:
    case NUM_INT:
    case NUM_REAL:
      p = parseBasic(parseExp);
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseBasic(boolean parseExp) throws ParseException {
        Expression e;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FALSE:
    case TRUE:
      e = parseBoolean();
      break;
    case CEIL:
    case FLOOR:
    case FUNCTION:
    case LOG:
    case MAX:
    case MIN:
    case MOD:
    case POW:
    case SQRT:
      e = parseFunction(parseExp);
      break;
    case IDENTIFIER:
      e = parseIdentifier();
      break;
    case NUM_INT:
      e = parseInt();
      break;
    case NUM_REAL:
      e = parseReal();
      break;
    case COALITION_OPEN:
      e = parseCoalition(parseExp);
      break;
    case P:
    case PMAX:
    case PMIN:
      e = parseProbQuant(parseExp);
      break;
    case R:
    case RMAX:
    case RMIN:
      e = parseRewQuant(parseExp);
      break;
    case S:
    case SMAX:
    case SMIN:
      e = parseSteadyQuant(parseExp);
      break;
    case LPAR:
      e = parseParenth(parseExp);
      break;
    case QUOTE:
      e = parseLabel();
      break;
    case FILTER:
      e = parseFilter(parseExp);
      break;
    case MULTIOBJECTIVE:
      e = parseMultiObjective(parseExp);
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseFunction(boolean parseExp) throws ParseException {
        Expression e;
        Expression ne;
        Operator type;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SQRT:
      e = parseSpecialFunction(parseExp);
      break;
    case MAX:
    case MIN:
      type = functionMultipleParams();
      jj_consume_token(LPAR);
      e = parseFunctionN(parseExp, type);
      jj_consume_token(RPAR);
      break;
    case LOG:
    case MOD:
    case POW:
      type = functionTwoParams();
      jj_consume_token(LPAR);
      e = parseFunction2(parseExp, type);
      jj_consume_token(RPAR);
      break;
    case CEIL:
    case FLOOR:
      type = functionOneParam();
      jj_consume_token(LPAR);
      e = parseFunction1(parseExp, type);
      jj_consume_token(RPAR);
      break;
    case FUNCTION:
      jj_consume_token(FUNCTION);
      jj_consume_token(LPAR);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SQRT:
        e = parseSqrt(parseExp);
        break;
      case MAX:
      case MIN:
        type = functionMultipleParams();
        jj_consume_token(COMMA);
        e = parseFunctionN(parseExp, type);
        break;
      case LOG:
      case MOD:
      case POW:
        type = functionTwoParams();
        jj_consume_token(COMMA);
        e = parseFunction2(parseExp, type);
        break;
      case CEIL:
      case FLOOR:
        type = functionOneParam();
        jj_consume_token(COMMA);
        e = parseFunction1(parseExp, type);
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(RPAR);
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseSpecialFunction(boolean parseExp) throws ParseException {
        Expression e;
    e = parseSqrt(parseExp);
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseSqrt(boolean parseExp) throws ParseException {
        Expression e;
        InfoExpression info = new InfoExpression(string);
    beginExpression(info);
    jj_consume_token(SQRT);
    jj_consume_token(LPAR);
    e = parseExp(parseExp);
    jj_consume_token(RPAR);
          endExpression(info);
          {if (true) return newOperator(OperatorPRISMPow.PRISM_POW, e,
                newLiteral("0.5", ExpressionTypeReal.TYPE_REAL),
                info);}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseFunctionN(boolean parseExp, Operator type) throws ParseException {
        Expression e;
        Expression ne;
        InfoExpression info = new InfoExpression(string);
    beginExpression(info);
    e = parseExp(parseExp);
    label_9:
    while (true) {
      jj_consume_token(COMMA);
      ne = parseExp(parseExp);
                  endExpression(info);
                  e = newOperator(type, e, ne, info);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[18] = jj_gen;
        break label_9;
      }
    }
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseFunction2(boolean parseExp, Operator type) throws ParseException {
        Expression e;
        Expression ne;
        InfoExpression info = new InfoExpression(string);
    beginExpression(info);
    e = parseExp(parseExp);
    jj_consume_token(COMMA);
    ne = parseExp(parseExp);
          endExpression(info);
          {if (true) return newOperator(type, e, ne, info);}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseFunction1(boolean parseExp, Operator type) throws ParseException {
        Expression e;
        InfoExpression info = new InfoExpression(string);
    beginExpression(info);
    e = parseExp(parseExp);
          endExpression(info);
          {if (true) return newOperator(type, e, info);}
    throw new Error("Missing return statement in function");
  }

  final private Operator functionMultipleParams() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MAX:
      jj_consume_token(MAX);
                  {if (true) return OperatorMax.MAX;}
      break;
    case MIN:
      jj_consume_token(MIN);
                  {if (true) return OperatorMin.MIN;}
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Operator functionOneParam() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FLOOR:
      jj_consume_token(FLOOR);
                  {if (true) return OperatorFloor.FLOOR;}
      break;
    case CEIL:
      jj_consume_token(CEIL);
                  {if (true) return OperatorCeil.CEIL;}
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Operator functionTwoParams() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case POW:
      jj_consume_token(POW);
                  {if (true) return OperatorPRISMPow.PRISM_POW;}
      break;
    case MOD:
      jj_consume_token(MOD);
                  {if (true) return OperatorMod.MOD;}
      break;
    case LOG:
      jj_consume_token(LOG);
                  {if (true) return OperatorLog.LOG;}
      break;
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Expression parseParenth(boolean parseExp) throws ParseException {
        Expression p;
    jj_consume_token(LPAR);
    p = parseExpTemporal(parseExp);
    jj_consume_token(RPAR);
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseIdentifier() throws ParseException {
        Token literal;
        InfoExpression info = new InfoExpression(string);
    beginExpression(info);
    literal = jj_consume_token(IDENTIFIER);
          endExpression(info);
          {if (true) return newIdentifier(literal, info);}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseLabel() throws ParseException {
        Token literal;
        InfoExpression info = new InfoExpression(string);
    beginExpression(info);
    jj_consume_token(QUOTE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      literal = jj_consume_token(IDENTIFIER);
      break;
    case INIT:
      literal = jj_consume_token(INIT);
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(QUOTE);
    endExpression(info);
          {if (true) return newIdentifier("\u005c"" + literal.toString() + "\u005c"", info);}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseReal() throws ParseException {
        Token real;
        InfoExpression info = new InfoExpression(string);
    beginExpression(info);
    real = jj_consume_token(NUM_REAL);
          endExpression(info);
        {if (true) return newLiteral(real, ExpressionTypeReal.TYPE_REAL, info);}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseInt() throws ParseException {
        Token intg;
        InfoExpression info = new InfoExpression(string);
    beginExpression(info);
    intg = jj_consume_token(NUM_INT);
          endExpression(info);
            {if (true) return newLiteral(intg, ExpressionTypeInteger.TYPE_INTEGER, info);}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseBoolean() throws ParseException {
        InfoExpression info = new InfoExpression(string);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
            beginExpression(info);
      jj_consume_token(TRUE);
                  endExpression(info);
                  {if (true) return newLiteral("true", ExpressionTypeBoolean.TYPE_BOOLEAN, info);}
      break;
    case FALSE:
            beginExpression(info);
      jj_consume_token(FALSE);
                  endExpression(info);
                {if (true) return newLiteral("false", ExpressionTypeBoolean.TYPE_BOOLEAN, info);}
      break;
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private OldSchoolFilter OldSchoolFilter() throws ParseException {
        Expression states;
        boolean min = false;
        boolean max = false;
        InfoExpression info = new InfoExpression(string);
    beginExpression(info);
    jj_consume_token(LCURL);
    states = parseExpTemporal(false);
    jj_consume_token(RCURL);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LCURL:
      jj_consume_token(LCURL);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MAX:
        jj_consume_token(MAX);
        jj_consume_token(RCURL);
                          max = true;
        break;
      case MIN:
        jj_consume_token(MIN);
        jj_consume_token(RCURL);
                          min = true;
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LCURL:
          jj_consume_token(LCURL);
          jj_consume_token(MAX);
          jj_consume_token(RCURL);
                                  max = true;
          break;
        default:
          jj_la1[24] = jj_gen;
          ;
        }
        break;
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[26] = jj_gen;
      ;
    }
                endExpression(info);
                FilterType type = null;
                if (!min && !max) {
                        type = FilterType.STATE;
                } else if (min && !max) {
                        type = FilterType.MIN;
                } else if (!min && max) {
                        type = FilterType.MAX;
                } else if (min && max) {
                        type = FilterType.RANGE;
                }
                {if (true) return new OldSchoolFilter(type, states, info);}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseCoalition(boolean parseExp) throws ParseException {
        Expression innerFormula;
        List<Expression> players = new ArrayList<Expression>();
        Token coal;
        Expression player;
        InfoExpression info = new InfoExpression(string);
    beginExpression(info);
    coal = jj_consume_token(COALITION_OPEN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      player = parseIdentifier();
      break;
    case NUM_INT:
      player = parseInt();
      break;
    default:
      jj_la1[27] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          players.add(player);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[28] = jj_gen;
        break label_10;
      }
      jj_consume_token(COMMA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        player = parseIdentifier();
        break;
      case NUM_INT:
        player = parseInt();
        break;
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                  players.add(player);
    }
    jj_consume_token(COALITION_CLOSE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case P:
    case PMAX:
    case PMIN:
      innerFormula = parseProbQuant(parseExp);
      break;
    case R:
    case RMAX:
    case RMIN:
      innerFormula = parseRewQuant(parseExp);
      break;
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          endExpression(info);
          {if (true) return newCoalition(innerFormula, players, info);}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseProbQuant(boolean parseExp) throws ParseException {
        Expression prop;
        Expression cmp;
        Expression cond = getTrue();
        DirType dirType;
        CmpType cmpType;
        OldSchoolFilter filter = null;
        InfoExpression info = new InfoExpression(string);
                if (parseExp) {
                        Token errorToken = getToken(1);
                        computeErrorPosition(errorToken.beginLine, errorToken.beginColumn);
                        ensure(false, ProblemsPRISM.EXPRESSION_PARSER_UNEXPECTED_LOGIC_OPERATOR, newPositional(errorLine, errorColumn), errorToken);
                        {if (true) return null;}
                }
                beginExpression(info);
    dirType = PropQuantProbDirType();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQ:
      jj_consume_token(EQ);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case QUESTION:
        jj_consume_token(QUESTION);
                                        cmpType = CmpType.IS;
                                        cmp = getTrue();
        break;
      case CEIL:
      case FALSE:
      case FILTER:
      case FLOOR:
      case FUNCTION:
      case F:
      case G:
      case LOG:
      case MAX:
      case MIN:
      case MOD:
      case MULTIOBJECTIVE:
      case P:
      case PMAX:
      case PMIN:
      case POW:
      case R:
      case RMAX:
      case RMIN:
      case S:
      case SMAX:
      case SMIN:
      case SQRT:
      case TRUE:
      case X:
      case MINUS:
      case LPAR:
      case NOT:
      case QUOTE:
      case COALITION_OPEN:
      case IDENTIFIER:
      case NUM_INT:
      case NUM_REAL:
        cmp = parseExpTemporal(parseExp);
                                  cmpType = CmpType.EQ;
        break;
      default:
        jj_la1[31] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(LBRACKET);
      prop = parseExpTemporal(parseExp);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COND:
        jj_consume_token(COND);
        cond = parseExpTemporal(parseExp);
        break;
      default:
        jj_la1[32] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LCURL:
        filter = OldSchoolFilter();
        break;
      default:
        jj_la1[33] = jj_gen;
        ;
      }
      jj_consume_token(RBRACKET);
      break;
    case LEQ:
    case LT:
    case GT:
    case GEQ:
      cmpType = PropQuantCmpType();
      cmp = parseExpTemporal(parseExp);
      jj_consume_token(LBRACKET);
      prop = parseExpTemporal(parseExp);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COND:
        jj_consume_token(COND);
        cond = parseExpTemporal(parseExp);
        break;
      default:
        jj_la1[34] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LCURL:
        filter = OldSchoolFilter();
        break;
      default:
        jj_la1[35] = jj_gen;
        ;
      }
      jj_consume_token(RBRACKET);
      break;
    default:
      jj_la1[36] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
            endExpression(info);
                Expression result = new ExpressionQuantifier.Builder()
                        .setDirType(dirType)
                        .setCmpType(cmpType)
                        .setQuantified(prop)
                        .setCompare(cmp)
                        .setCondition(cond)
                        .setPositional(info.toPositional())
                        .build();
                if (filter != null) {
                  result = new ExpressionFilter.Builder()
                                .setFilterType(filter.getType())
                                .setProp(result)
                                .setStates(filter.getStates())
                                .setPositional(filter.getInfo().toPositional())
                                .build();
                }
                {if (true) return result;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseSteadyQuant(boolean parseExp) throws ParseException {
        Expression prop;
        Expression cmp;
        Expression cond = getTrue();
        DirType dirType;
        CmpType cmpType;
        OldSchoolFilter filter = null;
        InfoExpression info = new InfoExpression(string);
                if (parseExp) {
                        Token errorToken = getToken(1);
                        computeErrorPosition(errorToken.beginLine, errorToken.beginColumn);
                        ensure(false, ProblemsPRISM.EXPRESSION_PARSER_UNEXPECTED_LOGIC_OPERATOR, newPositional(errorLine, errorColumn), errorToken.toString());
                        {if (true) return null;}
                }
                beginExpression(info);
    dirType = SteadyQuantProbDirType();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQ:
      jj_consume_token(EQ);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case QUESTION:
        jj_consume_token(QUESTION);
                                cmpType = CmpType.IS;
                                cmp = getTrue();
        break;
      case CEIL:
      case FALSE:
      case FILTER:
      case FLOOR:
      case FUNCTION:
      case F:
      case G:
      case LOG:
      case MAX:
      case MIN:
      case MOD:
      case MULTIOBJECTIVE:
      case P:
      case PMAX:
      case PMIN:
      case POW:
      case R:
      case RMAX:
      case RMIN:
      case S:
      case SMAX:
      case SMIN:
      case SQRT:
      case TRUE:
      case X:
      case MINUS:
      case LPAR:
      case NOT:
      case QUOTE:
      case COALITION_OPEN:
      case IDENTIFIER:
      case NUM_INT:
      case NUM_REAL:
        cmp = parseExpTemporal(parseExp);
                          cmpType = CmpType.EQ;
        break;
      default:
        jj_la1[37] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(LBRACKET);
      prop = parseExpTemporal(parseExp);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COND:
        jj_consume_token(COND);
        cond = parseExpTemporal(parseExp);
        break;
      default:
        jj_la1[38] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LCURL:
        filter = OldSchoolFilter();
        break;
      default:
        jj_la1[39] = jj_gen;
        ;
      }
      jj_consume_token(RBRACKET);
      break;
    case LEQ:
    case LT:
    case GT:
    case GEQ:
      cmpType = PropQuantCmpType();
      cmp = parseExpTemporal(parseExp);
      jj_consume_token(LBRACKET);
      prop = parseExpTemporal(parseExp);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COND:
        jj_consume_token(COND);
        cond = parseExpTemporal(parseExp);
        break;
      default:
        jj_la1[40] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LCURL:
        filter = OldSchoolFilter();
        break;
      default:
        jj_la1[41] = jj_gen;
        ;
      }
      jj_consume_token(RBRACKET);
      break;
    default:
      jj_la1[42] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
            endExpression(info);
                prop = new ExpressionSteadyState.Builder()
                        .setStates(prop)
                        .build();
                Expression result = new ExpressionQuantifier.Builder()
                        .setDirType(dirType)
                        .setCmpType(cmpType)
                        .setQuantified(prop)
                        .setCompare(cmp)
                        .setCondition(cond)
                        .setPositional(info.toPositional())
                        .build();
                if (filter != null) {
                        result = new ExpressionFilter.Builder()
                                .setFilterType(filter.getType())
                                .setProp(result)
                                .setStates(filter.getStates())
                                .setPositional(filter.getInfo().toPositional())
                                .build();
                }
                {if (true) return result;}
    throw new Error("Missing return statement in function");
  }

  final private CmpType PropQuantCmpType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LEQ:
      jj_consume_token(LEQ);
                  {if (true) return CmpType.LE;}
      break;
    case LT:
      jj_consume_token(LT);
                  {if (true) return CmpType.LT;}
      break;
    case GEQ:
      jj_consume_token(GEQ);
                  {if (true) return CmpType.GE;}
      break;
    case GT:
      jj_consume_token(GT);
                  {if (true) return CmpType.GT;}
      break;
    default:
      jj_la1[43] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Expression parseRewardPath(boolean parseExp, Expression rewardStructure) throws ParseException {
        Expression prop;
        Expression timebound;
        Expression discount;
        InfoExpression info = new InfoExpression(string);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case F:
            beginExpression(info);
      jj_consume_token(F);
      prop = parseExpTemporal(parseExp);
                  endExpression(info);
                  {if (true) return newRewardReachability(rewardStructure, prop, info);}
      break;
    case C:
          beginExpression(info);
      jj_consume_token(C);
                  timebound = ExpressionLiteral.getPosInf();
                  discount = null;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEQ:
        jj_consume_token(LEQ);
        timebound = parseExpTemporal(parseExp);
        break;
      default:
        jj_la1[44] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        jj_consume_token(COMMA);
        jj_consume_token(DISCOUNT);
        jj_consume_token(EQ);
        discount = parseExpTemporal(parseExp);
        break;
      default:
        jj_la1[45] = jj_gen;
        ;
      }
                  endExpression(info);
                        if (discount == null) {
                                {if (true) return newRewardCumulative(rewardStructure, timebound, info);}
                        } else {
                                {if (true) return newRewardDiscounted(rewardStructure, timebound, discount, info);}
                        }
      break;
    case I:
          beginExpression(info);
      jj_consume_token(I);
      jj_consume_token(EQ);
      prop = parseExpTemporal(parseExp);
                  endExpression(info);
                  {if (true) return newRewardInstantaneous(rewardStructure, prop, info);}
      break;
    case S:
          beginExpression(info);
      jj_consume_token(S);
                  endExpression(info);
                  {if (true) return newRewardSteadyState(rewardStructure, info);}
      break;
    default:
      jj_la1[46] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Expression parseRewardStructure(boolean parseExp) throws ParseException {
        Expression rewardStructure = null;
        Token literal;
    jj_consume_token(LCURL);
    if (jj_2_3(2147483647)) {
      jj_consume_token(QUOTE);
      literal = jj_consume_token(IDENTIFIER);
      jj_consume_token(QUOTE);
                  rewardStructure = newIdentifier("\u005c"" + literal.toString() + "\u005c"");
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CEIL:
      case FALSE:
      case FILTER:
      case FLOOR:
      case FUNCTION:
      case LOG:
      case MAX:
      case MIN:
      case MOD:
      case MULTIOBJECTIVE:
      case P:
      case PMAX:
      case PMIN:
      case POW:
      case R:
      case RMAX:
      case RMIN:
      case S:
      case SMAX:
      case SMIN:
      case SQRT:
      case TRUE:
      case MINUS:
      case LPAR:
      case NOT:
      case QUOTE:
      case COALITION_OPEN:
      case IDENTIFIER:
      case NUM_INT:
      case NUM_REAL:
        rewardStructure = parseExp(true);
        break;
      default:
        jj_la1[47] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(RCURL);
          {if (true) return rewardStructure;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseRewQuant(boolean parseExp) throws ParseException {
        Expression prop;
        Expression cmp;
        Expression cond = getTrue();
        DirType dirType;
        CmpType cmpType;
        Expression rewardStructure = getTrue();
        OldSchoolFilter filter = null;
        Token oper;
        InfoExpression info = new InfoExpression(string);
          beginExpression(info);
          oper = getToken(1);
                if (parseExp) {
                    ensure(false, ProblemsPRISM.EXPRESSION_PARSER_UNEXPECTED_LOGIC_OPERATOR, newPositional(oper.beginLine, oper.beginColumn),  oper.toString());
                    {if (true) return null;}
                }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case R:
      jj_consume_token(R);
                  dirType = DirType.NONE;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LCURL:
        rewardStructure = parseRewardStructure(parseExp);
        break;
      default:
        jj_la1[48] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MAX:
      case MIN:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MIN:
          jj_consume_token(MIN);
                          dirType = DirType.MIN;
          break;
        case MAX:
          jj_consume_token(MAX);
                          dirType = DirType.MAX;
          break;
        default:
          jj_la1[49] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[50] = jj_gen;
        ;
      }
      break;
    case RMIN:
      jj_consume_token(RMIN);
                  dirType = DirType.MIN;
      break;
    case RMAX:
      jj_consume_token(RMAX);
                  dirType = DirType.MAX;
      break;
    default:
      jj_la1[51] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQ:
                        cmpType = CmpType.IS;
                        cmp = getTrue();
      jj_consume_token(EQ);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case QUESTION:
        jj_consume_token(QUESTION);
                                cmpType = CmpType.IS;
                                cmp = getTrue();
        break;
      case CEIL:
      case FALSE:
      case FILTER:
      case FLOOR:
      case FUNCTION:
      case F:
      case G:
      case LOG:
      case MAX:
      case MIN:
      case MOD:
      case MULTIOBJECTIVE:
      case P:
      case PMAX:
      case PMIN:
      case POW:
      case R:
      case RMAX:
      case RMIN:
      case S:
      case SMAX:
      case SMIN:
      case SQRT:
      case TRUE:
      case X:
      case MINUS:
      case LPAR:
      case NOT:
      case QUOTE:
      case COALITION_OPEN:
      case IDENTIFIER:
      case NUM_INT:
      case NUM_REAL:
        cmp = parseExpTemporal(parseExp);
                          cmpType = CmpType.EQ;
        break;
      default:
        jj_la1[52] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case LEQ:
    case LT:
    case GT:
    case GEQ:
      cmpType = PropQuantCmpType();
      cmp = parseExpTemporal(parseExp);
      break;
    default:
      jj_la1[53] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(LBRACKET);
    prop = parseRewardPath(parseExp, rewardStructure);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COND:
      jj_consume_token(COND);
      cond = parseExpTemporal(parseExp);
      break;
    default:
      jj_la1[54] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LCURL:
      filter = OldSchoolFilter();
      break;
    default:
      jj_la1[55] = jj_gen;
      ;
    }
    jj_consume_token(RBRACKET);
          endExpression(info);
                Expression result = new ExpressionQuantifier.Builder()
                        .setDirType(dirType)
                        .setCmpType(cmpType)
                        .setQuantified(prop)
                        .setCompare(cmp)
                        .setCondition(cond)
                        .setPositional(info.toPositional())
                        .build();
                if (filter != null) {
                        result = new ExpressionFilter.Builder()
                                .setFilterType(filter.getType())
                                .setProp(result)
                                .setStates(filter.getStates())
                                .build();
                }
                {if (true) return result;}
    throw new Error("Missing return statement in function");
  }

  final public DirType PropQuantProbDirType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case P:
      jj_consume_token(P);
                  {if (true) return DirType.NONE;}
      break;
    case PMAX:
      jj_consume_token(PMAX);
                  {if (true) return DirType.MAX;}
      break;
    case PMIN:
      jj_consume_token(PMIN);
                  {if (true) return DirType.MIN;}
      break;
    default:
      jj_la1[56] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private DirType SteadyQuantProbDirType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case S:
      jj_consume_token(S);
                  {if (true) return DirType.NONE;}
      break;
    case SMAX:
      jj_consume_token(SMAX);
                  {if (true) return DirType.MAX;}
      break;
    case SMIN:
      jj_consume_token(SMIN);
                  {if (true) return DirType.MIN;}
      break;
    default:
      jj_la1[57] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private FilterType ExpressionFilterType() throws ParseException {
        FilterType type = null;
        Token id;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MIN:
      jj_consume_token(MIN);
                  type = FilterType.MIN;
      break;
    case MAX:
      jj_consume_token(MAX);
                  type = FilterType.MAX;
      break;
    case PLUS:
      jj_consume_token(PLUS);
                  type = FilterType.SUM;
      break;
    case AND:
      jj_consume_token(AND);
                  type = FilterType.FORALL;
      break;
    case OR:
      jj_consume_token(OR);
                  type = FilterType.EXISTS;
      break;
    case IDENTIFIER:
      id = jj_consume_token(IDENTIFIER);
                        switch (id.image) {
                                case "count" :
                                        type = FilterType.COUNT;
                                        break;
                                case "sum" :
                                        type = FilterType.SUM;
                                        break;
                                case "avg":
                                        type = FilterType.AVG;
                                        break;
                                case "first":
                                        type = FilterType.FIRST;
                                        break;
                                case "range":
                                        type = FilterType.RANGE;
                                        break;
                                case "forall":
                                        type = FilterType.FORALL;
                                        break;
                                case "exists":
                                        type = FilterType.EXISTS;
                                        break;
                                case "state":
                                        type = FilterType.STATE;
                                        break;
                                case "argmin":
                                        type = FilterType.ARGMIN;
                                        break;
                                case "argmax":
                                        type = FilterType.ARGMAX;
                                        break;
                                case "print":
                                        type = FilterType.PRINT;
                                        break;
                                case "printall":
                                        type = FilterType.PRINTALL;
                                        break;
                                default:
                                        computeErrorPosition(id.beginLine, id.beginColumn);
                                        ensure(false, ProblemsPRISM.EXPRESSION_PARSER_UNKNOWN_FILTER_TYPE, newPositional(errorLine, errorColumn), id.toString());
                        }
      break;
    default:
      jj_la1[58] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return type;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseFilter(boolean parseExp) throws ParseException {
        FilterType type;
        Expression prop;
        Expression states = getTrue();
        InfoExpression info = new InfoExpression(string);
                if (parseExp) {
                        Token errorToken = getToken(1);
                        computeErrorPosition(errorToken.beginLine, errorToken.beginColumn);
                        ensure(false, ProblemsPRISM.EXPRESSION_PARSER_UNEXPECTED_LOGIC_OPERATOR, newPositional(errorLine, errorColumn), errorToken.toString());
                }
          beginExpression(info);
    jj_consume_token(FILTER);
    jj_consume_token(LPAR);
    type = ExpressionFilterType();
    jj_consume_token(COMMA);
    prop = parseExpTemporal(parseExp);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      states = parseExpTemporal(parseExp);
      break;
    default:
      jj_la1[59] = jj_gen;
      ;
    }
    jj_consume_token(RPAR);
          endExpression(info);
          {if (true) return new ExpressionFilter.Builder()
                .setFilterType(type)
                .setProp(prop)
                .setStates(states)
                .setPositional(info.toPositional())
                .build();}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseMultiObjective(boolean parseExp) throws ParseException {
        Expression formula;
        List<Expression> list = new ArrayList<Expression>();
        InfoExpression info = new InfoExpression(string);
          beginExpression(info);
                if (parseExp) {
                        Token errorToken = getToken(1);
                        computeErrorPosition(errorToken.beginLine, errorToken.beginColumn);
                        ensure(false, ProblemsPRISM.EXPRESSION_PARSER_UNEXPECTED_LOGIC_OPERATOR, newPositional(errorLine, errorColumn), errorToken.toString());
                }
    jj_consume_token(MULTIOBJECTIVE);
    jj_consume_token(LPAR);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case P:
    case PMAX:
    case PMIN:
      formula = parseProbQuant(parseExp);
      break;
    case R:
    case RMAX:
    case RMIN:
      formula = parseRewQuant(parseExp);
      break;
    case S:
    case SMAX:
    case SMIN:
      formula = parseSteadyQuant(parseExp);
      break;
    default:
      jj_la1[60] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          list.add(formula);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[61] = jj_gen;
        break label_11;
      }
      jj_consume_token(COMMA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case P:
      case PMAX:
      case PMIN:
        formula = parseProbQuant(parseExp);
        break;
      case R:
      case RMAX:
      case RMIN:
        formula = parseRewQuant(parseExp);
        break;
      case S:
      case SMAX:
      case SMIN:
        formula = parseSteadyQuant(parseExp);
        break;
      default:
        jj_la1[62] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                  list.add(formula);
    }
    jj_consume_token(RPAR);
          endExpression(info);
          {if (true) return new ExpressionMultiObjective.Builder()
                .setOperands(list)
                .setPositional(info.toPositional())
                .build();}
    throw new Error("Missing return statement in function");
  }

//private Expression parseExpAsProp(boolean parseExp)  :
//{
//	Expression p;
//}
//{
//	p = parseTemporalBinary(parseExp)
//	{ return p; }
//}
  final public TimeBound TimeBound() throws ParseException {
        Expression left;
        Expression right;
        TimeBound timeBound = newTimeBound();
        boolean leftOpen = true;
        boolean rightOpen = true;
        InfoExpression info = new InfoExpression(string);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRACKET:
    case RBRACKET:
    case LEQ:
    case LT:
    case GT:
    case GEQ:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LT:
          beginExpression(info);
        jj_consume_token(LT);
        //		right = parseExpForTimeBound(true)
                        right = parseExp(true);
          endExpression(info);
                  timeBound = newTimeBound(ExpressionLiteral.getZero(), right, false, true, info);
        break;
      case LEQ:
          beginExpression(info);
        jj_consume_token(LEQ);
        //		right = parseExpForTimeBound(true)
                        right = parseExp(true);
          endExpression(info);
                  timeBound = newTimeBound(ExpressionLiteral.getZero(), right, false, false, info);
        break;
      case GT:
          beginExpression(info);
        jj_consume_token(GT);
        //		left = parseExpForTimeBound(true)
                        left = parseExp(true);
          endExpression(info);
                  timeBound = newTimeBound(left, ExpressionLiteral.getPosInf(), true, true, info);
        break;
      case GEQ:
          beginExpression(info);
        jj_consume_token(GEQ);
        //		left = parseExpForTimeBound(true)
                        left = parseExp(true);
          endExpression(info);
                  timeBound = newTimeBound(left, ExpressionLiteral.getPosInf(), false, true, info);
        break;
      case LBRACKET:
      case RBRACKET:
          beginExpression(info);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LBRACKET:
          jj_consume_token(LBRACKET);
                          leftOpen = false;
          break;
        case RBRACKET:
          jj_consume_token(RBRACKET);
                          leftOpen = true;
          break;
        default:
          jj_la1[63] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        left = parseExp(true);
        jj_consume_token(COMMA);
        right = parseExp(true);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case RBRACKET:
          jj_consume_token(RBRACKET);
                          rightOpen = false;
          break;
        case LBRACKET:
          jj_consume_token(LBRACKET);
                          rightOpen = true;
          break;
        default:
          jj_la1[64] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
          endExpression(info);
                  timeBound = newTimeBound(left, right, leftOpen, rightOpen, info);
        break;
      default:
        jj_la1[65] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[66] = jj_gen;
      ;
    }
          {if (true) return timeBound;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseTemporalBinary(boolean parseExp) throws ParseException {
        ArrayList<Expression> expressions = new ArrayList<Expression>();
        ArrayList<TimeBound> timeBounds = new ArrayList<TimeBound>();
        Expression p;
        TimeBound timeBound;
        BinType lastType = null;
        BinType type = null;
        Token oper;
        InfoExpression info = new InfoExpression(string);
          beginExpression(info);
    p = parseTemporalUnary(parseExp);
          expressions.add(p);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case R:
    case U:
    case W:
                  oper = getToken(1);
                        if (parseExp) {
                                Token errorToken = getToken(1);
                                computeErrorPosition(errorToken.beginLine, errorToken.beginColumn);
                                ensure(false, ProblemsPRISM.EXPRESSION_PARSER_UNEXPECTED_LOGIC_OPERATOR, newPositional(errorLine, errorColumn), errorToken.toString());
                        }
      type = TempBinType();
                        if (lastType != null) {
                                if (lastType != BinType.UNTIL || type != BinType.UNTIL) {
                                  ensure(false, ProblemsPRISM.PARSE_ERROR_MULTI_UNTIL, newPositional(token.endLine, token.endColumn), token.image);
                                }
                        }
                        lastType = type;
      timeBound = TimeBound();
                  timeBounds.add(timeBound);
      //		<LPAR>
                      p = parseTemporalBinary(parseExp);
                  expressions.add(p);
      break;
    default:
      jj_la1[67] = jj_gen;
      ;
    }
          endExpression(info);
                if (expressions.size() == 1) {
                        {if (true) return p;}
                } else {
                        switch (type) {
                        case RELEASE:
                                {if (true) return newTemporalRelease(expressions.get(0), expressions.get(1), timeBounds.get(0), info);}
                        case UNTIL:
                                {if (true) return newTemporalUntil(expressions.get(0), expressions.get(1), timeBounds.get(0), info);}
                        case WEAK: {
                                Expression or = or(expressions.get(0), expressions.get(1), null);
                                {if (true) return newTemporalRelease(expressions.get(1), or, timeBounds.get(0), info);}
                        }
                        default:
                                assert(false);
                                {if (true) return null;}
                        }
                }
    throw new Error("Missing return statement in function");
  }

  final private BinType TempBinType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case W:
      jj_consume_token(W);
                  {if (true) return BinType.WEAK;}
      break;
    case R:
      jj_consume_token(R);
                  {if (true) return BinType.RELEASE;}
      break;
    case U:
      jj_consume_token(U);
                  {if (true) return BinType.UNTIL;}
      break;
    default:
      jj_la1[68] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Expression parseTemporalUnary(boolean parseExp) throws ParseException {
        Expression p;
        UnType type;
        TimeBound timeBound;
        InfoExpression info = new InfoExpression(string);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case F:
    case G:
    case X:
          beginExpression(info);
                        if (parseExp) {
                                Token errorToken = getToken(1);
                                computeErrorPosition(errorToken.beginLine, errorToken.beginColumn);
                                ensure(false, ProblemsPRISM.EXPRESSION_PARSER_UNEXPECTED_LOGIC_OPERATOR, newPositional(errorLine, errorColumn), errorToken.toString());
                        }
      type = TempUnType();
      timeBound = TimeBound();
      //		<LPAR>
                      p = parseTemporalUnary(parseExp);
          endExpression(info);
                        switch (type) {
                        case NEXT:
                                p = newTemporalNext(p, timeBound, info);
                                break;
                        case FINALLY:
                                p = newTemporalFinally(p, timeBound, info);
                                break;
                        case GLOBALLY:
                                p = newTemporalGlobally(p, timeBound, info);
                                break;
                        }
      break;
    case CEIL:
    case FALSE:
    case FILTER:
    case FLOOR:
    case FUNCTION:
    case LOG:
    case MAX:
    case MIN:
    case MOD:
    case MULTIOBJECTIVE:
    case P:
    case PMAX:
    case PMIN:
    case POW:
    case R:
    case RMAX:
    case RMIN:
    case S:
    case SMAX:
    case SMIN:
    case SQRT:
    case TRUE:
    case MINUS:
    case LPAR:
    case NOT:
    case QUOTE:
    case COALITION_OPEN:
    case IDENTIFIER:
    case NUM_INT:
    case NUM_REAL:
      p = ExpressionITE(parseExp);
      break;
    default:
      jj_la1[69] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private UnType TempUnType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case X:
      jj_consume_token(X);
                  {if (true) return UnType.NEXT;}
      break;
    case F:
      jj_consume_token(F);
                  {if (true) return UnType.FINALLY;}
      break;
    case G:
      jj_consume_token(G);
                  {if (true) return UnType.GLOBALLY;}
      break;
    default:
      jj_la1[70] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_3_1() {
    if (jj_3R_12()) return true;
    if (jj_scan_token(COLON)) return true;
    return false;
  }

  private boolean jj_3R_12() {
    if (jj_scan_token(QUOTE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(103)) {
    jj_scanpos = xsp;
    if (jj_scan_token(25)) return true;
    }
    if (jj_scan_token(QUOTE)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(QUOTE)) return true;
    return false;
  }

  private boolean jj_3_2() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(68)) {
    jj_scanpos = xsp;
    if (jj_scan_token(69)) return true;
    }
    return false;
  }

  /** Generated Token Manager. */
  public PrismExpressionParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[71];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x3a0080,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3a0080,0x3a0080,0x100080,0x300080,0x0,0x0,0x100080,0x0,0x2000000,0x20000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x17a0080,0x0,0x0,0x0,0x0,0x0,0x17a0080,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20401000,0x3a0080,0x0,0x0,0x0,0x0,0x17a0080,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x17a0080,0x1400000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x8fc47a6a,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8fc47a6a,0x8fc47a6a,0x800406a,0x800406a,0x0,0x28,0x0,0x4042,0x0,0x80000000,0x0,0x28,0x0,0x0,0x0,0x0,0xc43800,0x8fc47a6a,0x0,0x0,0x0,0x0,0x0,0x8fc47a6a,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1000000,0x8fc47a6a,0x0,0x28,0x28,0xc40000,0x8fc47a6a,0x0,0x0,0x0,0x3800,0x7000000,0x28,0x0,0x7c43800,0x0,0x7c43800,0x0,0x0,0x0,0x0,0x40000,0x40000,0x8fc47a6a,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x10000,0x1000000,0x400000,0x800000,0x100000,0x80000,0x200820,0xc000000,0xc000000,0xf0000000,0xf0000000,0x30,0xc0,0xc0,0x820,0x800,0x0,0x0,0x40000,0x0,0x0,0x0,0x0,0x0,0x2000,0x0,0x2000,0x0,0x40000,0x0,0x0,0x1200824,0x8,0x2000,0x8,0x2000,0xf4000000,0x1200824,0x8,0x2000,0x8,0x2000,0xf4000000,0xf0000000,0x10000000,0x40000,0x0,0x200820,0x2000,0x0,0x0,0x0,0x1200824,0xf4000000,0x8,0x2000,0x0,0x0,0x180010,0x40000,0x0,0x40000,0x0,0x600,0x600,0xf0000600,0xf0000600,0x3,0x3,0x200824,0x4,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x389,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x389,0x389,0x0,0x0,0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x180,0x0,0x180,0x0,0x389,0x0,0x0,0x0,0x0,0x0,0x389,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x389,0x0,0x0,0x0,0x0,0x389,0x0,0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x389,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[3];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public PrismExpressionParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public PrismExpressionParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new PrismExpressionParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 71; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 71; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public PrismExpressionParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new PrismExpressionParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 71; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 71; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public PrismExpressionParser(PrismExpressionParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 71; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(PrismExpressionParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 71; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[108];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 71; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 108; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 3; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
