/* Generated By:JavaCC: Do not edit this line. HoaParserTokenManager.java */
package epmc.automaton.hoa;
import epmc.util.BitSet;
import epmc.util.BitSetUnboundedLongArray;
import java.util.Map;
import epmc.automaton.ProblemsAutomaton;
import static epmc.error.UtilError.ensure;
import epmc.expression.Expression;
import epmc.expression.standard.ExpressionOperator;
import epmc.expression.standard.ExpressionLiteral;
import epmc.operator.OperatorOr;
import epmc.operator.OperatorAnd;
import epmc.operator.OperatorNot;
import epmc.graph.explicit.GraphExplicitWrapper;
import epmc.util.UtilEscape;

/** Token Manager. */
public class HoaParserTokenManager implements HoaParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x7fffffdf0000L) != 0L)
         {
            jjmatchedKind = 50;
            return 3;
         }
         if ((active0 & 0x1800000200000L) != 0L)
            return 3;
         return -1;
      case 1:
         if ((active0 & 0x7ffffffb0000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 1;
            return 3;
         }
         if ((active0 & 0x40000L) != 0L)
            return 3;
         return -1;
      case 2:
         if ((active0 & 0x798bfcfa0000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 50;
               jjmatchedPos = 2;
            }
            return 3;
         }
         if ((active0 & 0x67402010000L) != 0L)
            return 3;
         return -1;
      case 3:
         if ((active0 & 0x7903fef80000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 3;
            return 3;
         }
         if ((active0 & 0x8800000000L) != 0L)
            return 3;
         return -1;
      case 4:
         if ((active0 & 0x79037ac00000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 4;
            return 3;
         }
         if ((active0 & 0x84080000L) != 0L)
            return 3;
         return -1;
      case 5:
         if ((active0 & 0x39017a400000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 5;
            return 3;
         }
         if ((active0 & 0x200000000L) != 0L)
            return 3;
         return -1;
      case 6:
         if ((active0 & 0x200040000000L) != 0L)
            return 3;
         if ((active0 & 0x19013a000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 6;
            return 3;
         }
         return -1;
      case 7:
         if ((active0 & 0x100010000000L) != 0L)
            return 3;
         if ((active0 & 0x9012a000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 7;
            return 3;
         }
         return -1;
      case 8:
         if ((active0 & 0x90128000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 8;
            return 3;
         }
         return -1;
      case 9:
         if ((active0 & 0x90128000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 9;
            return 3;
         }
         return -1;
      case 10:
         if ((active0 & 0x128000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 10;
            return 3;
         }
         return -1;
      case 11:
         if ((active0 & 0x128000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 11;
            return 3;
         }
         return -1;
      case 12:
         if ((active0 & 0x128000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 12;
            return 3;
         }
         return -1;
      case 13:
         if ((active0 & 0x128000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 13;
            return 3;
         }
         return -1;
      case 14:
         if ((active0 & 0x128000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 14;
            return 3;
         }
         return -1;
      case 15:
         if ((active0 & 0x128000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 15;
            return 3;
         }
         return -1;
      case 16:
         if ((active0 & 0x108000000L) != 0L)
            return 3;
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 16;
            return 3;
         }
         return -1;
      case 17:
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 17;
            return 3;
         }
         return -1;
      case 18:
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 18;
            return 3;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         return jjStopAtPos(0, 7);
      case 38:
         return jjStopAtPos(0, 8);
      case 40:
         return jjStopAtPos(0, 10);
      case 41:
         return jjStopAtPos(0, 11);
      case 44:
         return jjStopAtPos(0, 5);
      case 45:
         return jjMoveStringLiteralDfa1_0(0x300000000000L);
      case 61:
         return jjStopAtPos(0, 6);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x10001080000L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x40000000000L);
      case 72:
         return jjMoveStringLiteralDfa1_0(0x20000L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x20000000000L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x80000000L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x400040c00000L);
      case 91:
         return jjStopAtPos(0, 12);
      case 93:
         return jjStopAtPos(0, 13);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x402010000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x8000000000L);
      case 102:
         return jjStartNfaWithStates_0(0, 48, 3);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x128000000L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x3000000000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x800100000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x80200000000L);
      case 116:
         jjmatchedKind = 47;
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x40000L);
      case 123:
         return jjStopAtPos(0, 14);
      case 124:
         return jjStopAtPos(0, 9);
      case 125:
         return jjStopAtPos(0, 15);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa2_0(active0, 0x300000000000L);
      case 49:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(1, 18, 3);
         break;
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000L);
      case 80:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x2280100000L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x10002010000L);
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x128000000L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x41000000000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x400080000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x810200000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x400040c00000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L);
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      case 58:
         if ((active0 & 0x1000000L) != 0L)
            return jjStopAtPos(2, 24);
         break;
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000L);
      case 66:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000L);
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000c00000L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L);
      case 99:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x10006000000L);
      case 100:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 38, 3);
         break;
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L);
      case 102:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 41, 3);
         break;
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 108:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(2, 34, 3);
         break;
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000L);
      case 110:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 36, 3);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 42, 3);
         return jjMoveStringLiteralDfa3_0(active0, 0x928000000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000200000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x240000000L);
      case 120:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 37, 3);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
      case 58:
         if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(3, 17);
         break;
      case 66:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L);
      case 78:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000000L);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000000L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000L);
      case 101:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(3, 35, 3);
         return jjMoveStringLiteralDfa4_0(active0, 0x10168100000L);
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x280000000L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L);
      case 110:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 39, 3);
         break;
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000000L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000400000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x100000L) != 0L)
            return jjStopAtPos(4, 20);
         else if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(4, 21);
         break;
      case 68:
         return jjMoveStringLiteralDfa5_0(active0, 0x300000000000L);
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x480040400000L);
      case 105:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(4, 26, 3);
         break;
      case 110:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(4, 31, 3);
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L);
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x128000000L);
      case 115:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(4, 19, 3);
         break;
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x200800000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000000L);
      case 58:
         if ((active0 & 0x800000L) != 0L)
            return jjStopAtPos(5, 23);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStopAtPos(5, 46);
         break;
      case 89:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x12a000000L);
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000L);
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x10040000000L);
      case 121:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 33, 3);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 45:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 45, 3);
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000000L);
      case 58:
         if ((active0 & 0x400000L) != 0L)
            return jjStopAtPos(6, 22);
         break;
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000L);
      case 104:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000L);
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0x128000000L);
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L);
      case 116:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(6, 30, 3);
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 45:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 44, 3);
         break;
      case 101:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000L);
      case 105:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(7, 28, 3);
         return jjMoveStringLiteralDfa8_0(active0, 0x80128000000L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(8, 25);
         break;
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000000000L);
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000000000L);
      case 122:
         return jjMoveStringLiteralDfa9_0(active0, 0x128000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x10128000000L);
      case 115:
         return jjMoveStringLiteralDfa10_0(active0, 0x80000000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStopAtPos(10, 40);
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStopAtPos(10, 43);
         break;
      case 100:
         return jjMoveStringLiteralDfa11_0(active0, 0x128000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa12_0(active0, 0x128000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 66:
         return jjMoveStringLiteralDfa13_0(active0, 0x8000000L);
      case 82:
         return jjMoveStringLiteralDfa13_0(active0, 0x100000000L);
      case 99:
         return jjMoveStringLiteralDfa13_0(active0, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa14_0(active0, 0x100000000L);
      case 111:
         return jjMoveStringLiteralDfa14_0(active0, 0x20000000L);
      case 117:
         return jjMoveStringLiteralDfa14_0(active0, 0x8000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa15_0(active0, 0x20000000L);
      case 98:
         return jjMoveStringLiteralDfa15_0(active0, 0x100000000L);
      case 99:
         return jjMoveStringLiteralDfa15_0(active0, 0x8000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 66:
         return jjMoveStringLiteralDfa16_0(active0, 0x20000000L);
      case 104:
         return jjMoveStringLiteralDfa16_0(active0, 0x8000000L);
      case 105:
         return jjMoveStringLiteralDfa16_0(active0, 0x100000000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 105:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(16, 27, 3);
         break;
      case 110:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(16, 32, 3);
         break;
      case 117:
         return jjMoveStringLiteralDfa17_0(active0, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
private int jjMoveStringLiteralDfa17_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0);
      return 17;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa18_0(active0, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(16, active0);
}
private int jjMoveStringLiteralDfa18_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(16, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0);
      return 18;
   }
   switch(curChar)
   {
      case 104:
         return jjMoveStringLiteralDfa19_0(active0, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(17, active0);
}
private int jjMoveStringLiteralDfa19_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(17, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0);
      return 19;
   }
   switch(curChar)
   {
      case 105:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(19, 29, 3);
         break;
      default :
         break;
   }
   return jjStartNfa_0(18, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 11;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff200000000000L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(3);
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(0, 2);
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(1);
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 49)
                        kind = 49;
                  }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if (curChar == 48 && kind > 49)
                     kind = 49;
                  break;
               case 3:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(3);
                  break;
               case 5:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 34)
                     jjCheckNAddStates(0, 2);
                  break;
               case 8:
                  jjCheckNAddStates(0, 2);
                  break;
               case 9:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 10:
                  if (curChar == 34 && kind > 52)
                     kind = 52;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(3);
                  }
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 3:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(3);
                  break;
               case 4:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 5:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 7:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 8:
                  jjCheckNAddStates(0, 2);
                  break;
               case 9:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 8:
               case 9:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 11 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   7, 9, 10, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\54", "\75", "\41", "\46", "\174", "\50", "\51", 
"\133", "\135", "\173", "\175", "\141\143\143", "\110\117\101\72", "\166\61", 
"\101\154\151\141\163", "\156\141\155\145\72", "\164\157\157\154\72", "\123\164\141\164\145\163\72", 
"\123\164\141\162\164\72", "\101\120\72", "\141\143\143\55\156\141\155\145\72", "\102\165\143\150\151", 
"\147\145\156\145\162\141\154\151\172\145\144\55\102\165\143\150\151", "\143\157\55\102\165\143\150\151", 
"\147\145\156\145\162\141\154\151\172\145\144\55\143\157\55\102\165\143\150\151", "\123\164\162\145\145\164\164", "\122\141\142\151\156", 
"\147\145\156\145\162\141\154\151\172\145\144\55\122\141\142\151\156", "\160\141\162\151\164\171", "\141\154\154", "\156\157\156\145", 
"\155\151\156", "\155\141\170", "\157\144\144", "\145\166\145\156", 
"\101\143\143\145\160\164\141\156\143\145\72", "\111\156\146", "\106\151\156", "\160\162\157\160\145\162\164\151\145\163\72", 
"\55\55\102\117\104\131\55\55", "\55\55\105\116\104\55\55", "\123\164\141\164\145\72", "\164", "\146", null, 
null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x1fffffffffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[11];
private final int[] jjstateSet = new int[22];
protected char curChar;
/** Constructor. */
public HoaParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public HoaParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 11; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
